### ISSUE TITLE
[bug]1.20.1-0.5.4-2-Crash on startup

### ISSUE THREAD

**Issue by Git-Reternos** [timplay33/Create-Mobile-Packages#204]
**Describe the bug**
Crash on startup

**To Reproduce**
1. Play on my modpack
2. Click on Play
3. Waiting for launch
4. error pop up

**Expected behavior**
Launch succesful

**Screenshots**

![Image](https://github.com/user-attachments/assets/6f86a022-4457-46a3-8c86-b91db3fcf18a)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows11-24H2]
 - Forge version: [min. 47.4.2]
 - Create version: [min. 6.0.6]
 - Create: Mobile Packages version: [e.g. 0.5.4-2]

**Crash log**
[crash-2025-06-24_08.54.08-fml.txt](https://github.com/user-attachments/files/20874142/crash-2025-06-24_08.54.08-fml.txt)

**Additional context**
Recommand import it by using ATLauncher
mymodpack

[Server-Pocket-1.3 1.20.1.zip](https://github.com/user-attachments/files/20874360/Server-Pocket-1.3.1.20.1.zip)

**Comment by timplay33** [comment]
Fixed on Hotfix 0.5.4-3

**Comment by Git-Reternos** [comment]
After i reinstall and update to 0.5.4-3, Create: Mobile Packages still crash my game too

[crash-2025-06-24_22.59.18-client.txt](https://github.com/user-attachments/files/20886191/crash-2025-06-24_22.59.18-client.txt)

**Comment by Git-Reternos** [comment]
Showing sth relate to Caverns & Chasms so i try remove it. But game still crash

[crash-2025-06-24_23.04.20-client.txt](https://github.com/user-attachments/files/20886275/crash-2025-06-24_23.04.20-client.txt)

**Comment by timplay33** [comment]
Fixed with Hotfix 0.5.4-4
