### ISSUE TITLE
[bug] Create 6.0.8 not working

### ISSUE THREAD

**Issue by GamerMP523** [timplay33/Create-Mobile-Packages#247]
You cant use the latest relese with create 6.0.8
Add the Crash log if possible

i am using amethyst on ios but i think the issue is on desktop too

[latestlog.txt](https://github.com/user-attachments/files/23434701/latestlog.txt)

**Comment by GamerMP523** [comment]
btw. this is an client only issue. On an server there is no problem

**Comment by timplay33** [comment]
Hi there, support for create 6.0.7 and above is at the moment only in the beta versions. Try out the beta 2 which should fix the issue

**Comment by GamerMP523** [comment]
> Hi there, support for create 6.0.7 and above is at the moment only in the beta versions. Try out the beta 2 which should fix the issue

The Beta 2 didnt fix the issue. It coud be caused because of an new neoforge version too..
