### ISSUE TITLE
[bug] latest release/beta version is not working with the latest neoforge version (I think)

### ISSUE THREAD

**Issue by GamerMP523** [timplay33/Create-Mobile-Packages#248]
I think the newest version of neoforge is causing issues

[latestlog.txt](https://github.com/user-attachments/files/23434876/latestlog.txt)

**Comment by timplay33** [comment]
Does the issue persist without Create: Mobile Packages? On first look, I can't seem to find a direct error from CMP

**Comment by GamerMP523** [comment]
> Does the issue persist without Create: Mobile Packages? On first look, I can't seem to find a direct error from CMP

<img width="1210" height="834" alt="Image" src="https://github.com/user-attachments/assets/a07cdc97-4890-4d61-81f3-f02b393167fb" />

**Comment by timplay33** [comment]
> > Does the issue persist without Create: Mobile Packages? On first look, I can't seem to find a direct error from CMP
> 
> <img alt="Image" width="1210" height="834" src="https://private-user-images.githubusercontent.com/178880215/511821930-a07cdc97-4890-4d61-81f3-f02b393167fb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI3MTUxMjMsIm5iZiI6MTc2MjcxNDgyMywicGF0aCI6Ii8xNzg4ODAyMTUvNTExODIxOTMwLWEwN2NkYzk3LTQ4OTAtNGQ2MS04MWYzLWYwMmIzOTMxNjdmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOVQxOTAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTQzNTk4NzdhZjcwYWQ0OTU5NzA0MWUyNGQyYjljNjUxMmJlMTY3Mzk3MzgwZmRlYjgzZTdkOGExZDZlYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MaruZvk_VQjCL6j5uC5FVoDTvQaQFzLj3vyCLXFQj7Q">

But this error was fixed in Beta 2. The create devs removed a Class this mod uses, but in Beta 2 I no longer use it.

**Comment by GamerMP523** [comment]
> > > Does the issue persist without Create: Mobile Packages? On first look, I can't seem to find a direct error from CMP
> > 
> > 
> > <img alt="Image" width="1210" height="834" src="https://private-user-images.githubusercontent.com/178880215/511821930-a07cdc97-4890-4d61-81f3-f02b393167fb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI3MTUxMjMsIm5iZiI6MTc2MjcxNDgyMywicGF0aCI6Ii8xNzg4ODAyMTUvNTExODIxOTMwLWEwN2NkYzk3LTQ4OTAtNGQ2MS04MWYzLWYwMmIzOTMxNjdmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwOVQxOTAwMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTQzNTk4NzdhZjcwYWQ0OTU5NzA0MWUyNGQyYjljNjUxMmJlMTY3Mzk3MzgwZmRlYjgzZTdkOGExZDZlYTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MaruZvk_VQjCL6j5uC5FVoDTvQaQFzLj3vyCLXFQj7Q">
> 
> But this error was fixed in Beta 2. The create devs removed a Class this mod uses, but in Beta 2 I no longer use it.

When I remove Mobile Packeges from the mod list it still crashes! This time it says that it is Creates fault.

<img width="1210" height="834" alt="Image" src="https://github.com/user-attachments/assets/ff053d4f-478a-4042-b60a-dc6778251361" />

[latestlog.txt](https://github.com/user-attachments/files/23442495/latestlog.txt)

**Comment by timplay33** [comment]
Ok, sorry but I can't help with create issues. Try opening an issue with them.

**Comment by GamerMP523** [comment]
Neoforge Version 21.1.212 is the latest version that works
