### ISSUE TITLE
RoboBees stop working after 1 delivery

### ISSUE THREAD

**Issue by JetStorm91** [timplay33/Create-Mobile-Packages#249]
**Describe the bug**
I've got a network of Beeports that allow my robobees to carry items to the named destinations, however, within the current beta and after following the steps to get them to work, the bees will deliver 1 package before heading to a nearby port and start entering and exiting continuously

**To Reproduce**
1. Create an automatic network including a factory gauge
2. link the ports and bees to the network
3. deploy the bees
4. wait and watch

**Expected behavior**
the bees fly around to the beeports that have packages waiting and taking them to their destination before going back to get more and continuing the process

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Forge version: 47.4.10
 - Create version: 6.0.8
 - Create: Mobile Packages version: v0.6.0-Beta-02

**Comment by JetStorm91** [comment]
https://www.dropbox.com/scl/fi/qzc01ca4e7ed9bqcbi26r/2025-11-24-08-07-42.mp4?rlkey=ttqnh1zrazkxagfvb6a1cuf2p&dl=0

a link to a video showing exactly what I'm describing

**Comment by timplay33** [comment]
This should be fixed in the new beta3, that will release today or tomorrow, as I rewrote how bees are requested if a port needs one

**Comment by timplay33** [comment]
Fixed in beta-3 (I believe), now available!

Modrinth: https://modrinth.com/mod/create-mobile-packages/versions
Curseforge: https://www.curseforge.com/minecraft/mc-mods/create-mobile-packages/files/all

**Comment by JetStorm91** [comment]
it's partially fixed, some bees do go around delivering, but other bees that cannot find a job, even though there are delivery jobs, they still do this

**Comment by JetStorm91** [comment]
Alright, i've just done some experimentation, looks like the robobees also have some issues with their Y-Axis jobfinding, example, i have a storage port at y-axis 77 and deposit ports at y-axis' 84, 77 and 71, they return from the further distanced y-84 and 77, but not from the closer y-71 ports

**Comment by timplay33** [comment]
caused by #301
