### ISSUE TITLE
[NEO 1.21.1] Opening the Drone Controller kicks the client from the server

### ISSUE THREAD

**Issue by kil0byt3** [timplay33/Create-Mobile-Packages#54]
**Describe the bug**
Opening a linked Drone Controller shows the Stock List screen for a second, then immediately kicks the client from the server. (tried my main network with many items, and a separate network with a single item in a chest)

**To Reproduce**
1. Link Drone Controller to a network 
2. Right-click with the Drone controller
3. Kicked from server

**Expected behavior**
Not to be kicked and to see an item list presented

**Screenshots**
N/A

**Desktop**
 - OS: W11
 - NeoForge: 21.1.161
 - Create version: 6.0.4
 - Create: Mobile Packages version: 0.4.1

**Crash log**
https://mclo.gs/9OAeZgT

That should include mod list as well but here's that just in case:

https://pastebin.com/raw/zQifa61h

**Comment by timplay33** [comment]
Fixed on Dev. I will release soon

**Comment by kil0byt3** [comment]
Appreciate it!

**Comment by kil0byt3** [comment]
Seems this issue is still happening. 

Logs of the disconnect that is occurring with 0.4.2 (I believe the error is similar): 

https://mclo.gs/ZAt6otC

Additionally, the "link" behaviour of the Drone Controller seems to be off; "Shift+Right-Click" no longer binds the controller, instead it seems like just a normal Right-Click binds to a Stock Link. I will open a new issue for this, for tracking.

**Comment by timplay33** [comment]
@kil0byt3 if looked into it. Could you verify for me if this version works for you? https://ci.theidler.de/job/Create-Mobile-Packages/job/mc1.21.1%252Fbugfix%252F%252354/lastSuccessfulBuild/artifact/build/libs/create_mobile_packages-1.21.1-0.4.2-1-mc1.21.1_bugfix__54.jar

**Comment by kil0byt3** [comment]
I can test this on my server within a couple of hours and will let you know. Thanks

**Comment by kil0byt3** [comment]
Issue solved on the dev build you provided 👍🏻
